//! Patch-contig alias table generator for `vareffect-cli setup`.
//!
//! MANE summary TSV references patch scaffolds by RefSeq accession
//! (`NW_*`, `NT_*`); the MANE GFF3 uses UCSC contig names
//! (`chr9_KN196479v1_fix`, `chr22_KI270879v1_alt`, …). This module builds a
//! RefSeq→UCSC mapping table from the NCBI assembly report so the
//! transcript-models cross-validation pass can reconcile the two forms.
//!
//! Only patch scaffolds are emitted (`NW_*`/`NT_*`). Primary chromosomes
//! (`NC_*`) already have a hardcoded table in
//! `vareffect::chrom::refseq_to_ucsc`, and rows with a UCSC sentinel of
//! `na` have no cross-validation target. Columns (0-indexed): `6` is
//! `RefSeq-Accn`, `9` is `UCSC-style-name`.

use std::collections::HashMap;
use std::fs::File;
use std::io::{BufRead, BufReader, Write};
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};

/// Default output filename produced by [`build_from_assembly_report`]
/// when callers don't override via the per-assembly config. The default
/// targets the GRCh38 layout because that's the only assembly that ever
/// falls back to a hard-coded default; GRCh37 always supplies an
/// explicit `patch_aliases_filename` via the per-assembly config.
#[allow(dead_code)]
pub const DEFAULT_OUTPUT_FILENAME: &str = "patch_chrom_aliases_grch38.csv";

/// Parse the NCBI assembly report at `report_path` and write a 2-column
/// `refseq,ucsc` CSV to `{output_dir}/{output_filename}`. Returns
/// `(output_path, row_count)`. The write is atomic via `.tmp` + rename.
///
/// `output_filename` is config-driven so GRCh37 and GRCh38 builds can
/// produce side-by-side `patch_chrom_aliases_grch37.csv` /
/// `patch_chrom_aliases_grch38.csv` files in the same `output_dir`.
///
/// # Errors
///
/// Fails if `report_path` cannot be read or the output cannot be written.
pub fn build_from_assembly_report(
    report_path: &Path,
    output_dir: &Path,
    output_filename: &str,
) -> Result<(PathBuf, usize)> {
    std::fs::create_dir_all(output_dir)
        .with_context(|| format!("creating {}", output_dir.display()))?;

    let file =
        File::open(report_path).with_context(|| format!("opening {}", report_path.display()))?;
    let reader = BufReader::new(file);

    let mut rows: Vec<(String, String)> = Vec::new();
    for line_result in reader.lines() {
        let line = line_result.with_context(|| "reading assembly report line")?;
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        let cols: Vec<&str> = line.split('\t').collect();
        // Need column 10 (UCSC name); skip malformed short rows.
        if cols.len() < 10 {
            continue;
        }
        let refseq = cols[6].trim();
        let ucsc = cols[9].trim();
        if ucsc.is_empty() || ucsc == "na" {
            continue;
        }
        // Patch scaffolds only; primary chroms live in vareffect::chrom.
        if !(refseq.starts_with("NW_") || refseq.starts_with("NT_")) {
            continue;
        }
        rows.push((refseq.to_string(), ucsc.to_string()));
    }

    // Deterministic output order.
    rows.sort_by(|a, b| a.0.cmp(&b.0));

    let row_count = rows.len();
    let output_path = output_dir.join(output_filename);
    let tmp_path = output_dir.join(format!("{output_filename}.tmp"));

    {
        let mut out =
            File::create(&tmp_path).with_context(|| format!("creating {}", tmp_path.display()))?;
        writeln!(
            out,
            "# Patch-contig aliases: RefSeq accession -> UCSC contig name (GRCh37 or GRCh38)."
        )?;
        writeln!(
            out,
            "# Generated by `vareffect-cli setup` from the NCBI assembly report."
        )?;
        writeln!(
            out,
            "# Do not hand-edit -- rerun vareffect-cli setup to refresh."
        )?;
        writeln!(out, "refseq,ucsc")?;
        for (refseq, ucsc) in &rows {
            writeln!(out, "{refseq},{ucsc}")?;
        }
        out.sync_all()
            .with_context(|| format!("sync {}", tmp_path.display()))?;
    }

    std::fs::rename(&tmp_path, &output_path).with_context(|| {
        format!(
            "renaming {} -> {}",
            tmp_path.display(),
            output_path.display()
        )
    })?;

    Ok((output_path, row_count))
}

/// Load a per-assembly `patch_chrom_aliases_grch{37,38}.csv` into a
/// `HashMap` keyed on RefSeq accession. Tolerates `#` comments, the
/// header row, blank lines, and whitespace. Duplicate keys keep the
/// last value. Errors (with a `vareffect setup` hint) if the file is
/// missing or empty.
pub fn load(path: &Path) -> Result<HashMap<String, String>> {
    let file = File::open(path).with_context(|| {
        format!(
            "opening patch-alias CSV {} — run `vareffect-cli setup` to generate it",
            path.display()
        )
    })?;
    let reader = BufReader::new(file);
    let mut map: HashMap<String, String> = HashMap::new();
    for line_result in reader.lines() {
        let line = line_result.with_context(|| format!("reading {}", path.display()))?;
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') || trimmed.starts_with("refseq,") {
            continue;
        }
        let Some((refseq, ucsc)) = trimmed.split_once(',') else {
            // Malformed row — skip (only fires on hand edits).
            continue;
        };
        let refseq = refseq.trim().to_string();
        let ucsc = ucsc.trim().to_string();
        if refseq.is_empty() || ucsc.is_empty() {
            continue;
        }
        map.insert(refseq, ucsc);
    }
    if map.is_empty() {
        bail!("patch-alias CSV {} contained no rows", path.display());
    }
    Ok(map)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::TempDir;

    /// Fixture covering: header lines, primary-chrom row (skipped), a kept
    /// patch row, a `na` UCSC patch row (skipped), and a short garbage row.
    const MINI_REPORT: &str = "\
# Assembly Name:  GRCh38.p14
# Assembly Accession: GCF_000001405.40
# Sequence-Name\tSequence-Role\tAssigned-Molecule\tAssigned-Molecule-Location/Type\tGenBank-Accn\tRelationship\tRefSeq-Accn\tAssembly-Unit\tSequence-Length\tUCSC-style-name
1\tassembled-molecule\t1\tChromosome\tCM000663.2\t=\tNC_000001.11\tPrimary Assembly\t248956422\tchr1
HSCHR1_1_CTG3\tfix-patch\t1\tChromosome\tKN196472.1\t=\tNW_009646194.1\tPATCHES\t461159\tchr1_KN196472v1_fix
HG2216_PATCH\tfix-patch\t9\tChromosome\tKN538363.1\t=\tNW_011332691.1\tPATCHES\t159547\tna
ONLY_FEW_COLUMNS\tassembled-molecule
HSCHR22_3_CTG1\talt-scaffold\t22\tChromosome\tKI270879.1\t=\tNT_187633.1\tALT_REF_LOCI_30\t304135\tchr22_KI270879v1_alt
";

    fn write_temp(contents: &str) -> (TempDir, PathBuf) {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join("assembly_report.txt");
        File::create(&path)
            .unwrap()
            .write_all(contents.as_bytes())
            .unwrap();
        (tmp, path)
    }

    #[test]
    fn build_from_assembly_report_extracts_only_patch_rows_with_ucsc_names() {
        let (_tmp_in, report_path) = write_temp(MINI_REPORT);
        let out_dir = tempfile::tempdir().unwrap();

        let (csv_path, count) =
            build_from_assembly_report(&report_path, out_dir.path(), DEFAULT_OUTPUT_FILENAME)
                .expect("build");

        assert_eq!(count, 2, "expected 2 patch rows (NC_ skipped, na skipped)");
        assert_eq!(csv_path.file_name().unwrap(), DEFAULT_OUTPUT_FILENAME);

        let contents = std::fs::read_to_string(&csv_path).unwrap();
        // Header preserved.
        assert!(contents.contains("refseq,ucsc"));
        // Two real patch rows survived, sorted by RefSeq accession.
        let data_lines: Vec<&str> = contents
            .lines()
            .filter(|l| !l.starts_with('#') && !l.is_empty() && !l.starts_with("refseq,"))
            .collect();
        assert_eq!(
            data_lines,
            vec![
                "NT_187633.1,chr22_KI270879v1_alt",
                "NW_009646194.1,chr1_KN196472v1_fix",
            ]
        );
        // Primary chromosome row is absent.
        assert!(!contents.contains("NC_000001.11"));
        assert!(!contents.contains("chr1,"));
        // The `na` UCSC row is absent.
        assert!(!contents.contains("NW_011332691.1"));
    }

    #[test]
    fn load_round_trips_build_output() {
        let (_tmp_in, report_path) = write_temp(MINI_REPORT);
        let out_dir = tempfile::tempdir().unwrap();
        let (csv_path, _) =
            build_from_assembly_report(&report_path, out_dir.path(), DEFAULT_OUTPUT_FILENAME)
                .unwrap();

        let map = load(&csv_path).expect("load");
        assert_eq!(map.len(), 2);
        assert_eq!(
            map.get("NW_009646194.1").map(String::as_str),
            Some("chr1_KN196472v1_fix")
        );
        assert_eq!(
            map.get("NT_187633.1").map(String::as_str),
            Some("chr22_KI270879v1_alt")
        );
    }

    #[test]
    fn load_tolerates_hand_edits_and_whitespace() {
        let tmp = tempfile::tempdir().unwrap();
        let csv_path = tmp.path().join("patch_chrom_aliases_grch38.csv");
        let contents = "\
# Comment line
# Another comment

refseq,ucsc
NW_100.1 , chr1_KI100v1_fix
  NW_200.1,chr2_KI200v1_fix
NW_300.1,
,chr4_X
";
        File::create(&csv_path)
            .unwrap()
            .write_all(contents.as_bytes())
            .unwrap();

        let map = load(&csv_path).expect("load");
        // Only rows with both fields non-empty should land.
        assert_eq!(map.len(), 2);
        assert_eq!(
            map.get("NW_100.1").map(String::as_str),
            Some("chr1_KI100v1_fix")
        );
        assert_eq!(
            map.get("NW_200.1").map(String::as_str),
            Some("chr2_KI200v1_fix")
        );
    }

    #[test]
    fn load_rejects_empty_file() {
        let tmp = tempfile::tempdir().unwrap();
        let csv_path = tmp.path().join("empty.csv");
        File::create(&csv_path)
            .unwrap()
            .write_all(b"# only a comment\nrefseq,ucsc\n")
            .unwrap();

        let err = load(&csv_path).unwrap_err();
        assert!(
            format!("{err:#}").contains("contained no rows"),
            "expected empty-file error, got {err:#}"
        );
    }

    #[test]
    fn load_missing_file_hints_at_vareffect_cli_setup() {
        let tmp = tempfile::tempdir().unwrap();
        let csv_path = tmp.path().join("nonexistent.csv");
        let err = load(&csv_path).unwrap_err();
        assert!(
            format!("{err:#}").contains("vareffect-cli setup"),
            "expected vareffect-cli setup hint in error, got {err:#}"
        );
    }
}
